### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by Ferwol** [kevinferrare/arduino-st4#12]
Hi!
I am having a hard time making st4 work. When I try to connect I get a time out error
![IMG20210815143733 (1)](https://user-images.githubusercontent.com/88989503/129543719-2b8363d7-3ab6-4e22-aaf0-8b2fec2fc0f3.jpg)

![IMG20210815143722 (1)](https://user-images.githubusercontent.com/88989503/129543859-731d8c4b-9609-4fbd-bc9e-e1523a5509d2.jpg)

![IMG20210815143837 (1)](https://user-images.githubusercontent.com/88989503/129543773-f28ddb89-5537-4b81-9912-6a69451726bc.jpg)
Already tried changing COM baudrate to 57600 and nothing happens.
What am I doing wrong?
Thanks!

**Comment by kevinferrare** [comment]
Are you able to send commands through the arduino IDE as suggested in the readme?

**Comment by Ferwol** [comment]
Yes, and I see "OK#" after sending commands

**Comment by Ferwol** [comment]
Should I try an older version of Ascom platform? I am stuck with this error 😵😵

**Comment by Ferwol** [comment]
I am using a ch340 Arduino Nano. On a couple of days will be trying with an original one.

**Comment by Ferwol** [comment]
Well, It seems that one problem was I was using a copy if Nano and not the original. Now I can connect Cartes du ciel to st4. Phd2 is being a bit more tricky, but that is a different issue.
Thanks for the attention!
